---
deployment:
  tasks:
    - export DEPLOYPATH=/home/openoiip/basangroup.com/
    - /bin/cp -R includes $DEPLOYPATH
    - /bin/cp -R index.php $DEPLOYPATH
    - /bin/cp -R about.php $DEPLOYPATH
    - /bin/cp -R contact.php $DEPLOYPATH
    - /bin/cp -R news.php $DEPLOYPATH
    - /bin/cp -R services.php $DEPLOYPATH